In [12]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split

data = pd.read_csv('C:/Users/abdal/Desktop/Winter 2022/BMEN 415/Project/Classification/Classification_Diabetes_Dataset.csv')

### Outcome = 1 means patient has diabetes
### Outcome = 0 means patient does not have diabetes
df = pd.DataFrame(data)

x=df.iloc[:,0:8]
y=df.iloc[:,8]
x_train, x_test, y_train, y_test = train_test_split(x,y,train_size=0.8, random_state=5)
#print(x.head())
#print(y.head())
#x_train.shape
y_test.shape

(154,)

In [11]:
### Quadratic Discriminant Analysis

from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis
from sklearn.metrics import accuracy_score, confusion_matrix

qda=QuadraticDiscriminantAnalysis()
qda.fit(x_train,y_train)

y_predict_test = qda.predict(x_test)

acc = accuracy_score(y_test, y_predict_test)
cm = confusion_matrix(y_test,y_predict_test)

print('Accuracy:',acc)
print('Confusion Matrix:\n',cm)

Accuracy: 0.7792207792207793
Confusion Matrix:
 [[84 16]
 [18 36]]


In [14]:
### Hist Gradient Boosting 

from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import accuracy_score, confusion_matrix

gbc=GradientBoostingClassifier()
gbc.fit(x_train,y_train)

y_predict_test = gbc.predict(x_test)

acc = accuracy_score(y_test, y_predict_test)
cm = confusion_matrix(y_test,y_predict_test)

print('Accuracy:',acc)
print('Confusion Matrix:\n',cm)

Accuracy: 0.7727272727272727
Confusion Matrix:
 [[89 11]
 [24 30]]


In [16]:
### Stochastic Gradient Descent

from sklearn.linear_model import SGDClassifier
from sklearn.metrics import accuracy_score, confusion_matrix

sgd=SGDClassifier()
sgd.fit(x_train,y_train)

y_predict_test = sgd.predict(x_test)

acc = accuracy_score(y_test, y_predict_test)
cm = confusion_matrix(y_test,y_predict_test)

print('Accuracy:',acc)
print('Confusion Matrix:\n',cm)

Accuracy: 0.577922077922078
Confusion Matrix:
 [[45 55]
 [10 44]]
